export default

[
  {
    "first_name": "Soledad",
    "last_name": "Mockus",
    "company_name": "Sinclair Machine Products Inc",
    "address": "75 Elm Rd #1190",
    "state": "ACT",
    "post": 2600,
    "city": "Barton",
    "phone1": "02-1291-8182",
    "phone2": "0444-126-746",
    "email": "soledad_mockus@yahoo.com",
    "web": "http://www.sinclairmachineproductsinc.com.au"
  },
  {
    "first_name": "Dana",
    "last_name": "Vock",
    "company_name": "Fried, Monte Esq",
    "address": "49 Walnut St",
    "state": "ACT",
    "post": 2600,
    "city": "Yarralumla",
    "phone1": "02-6689-1150",
    "phone2": "0411-398-917",
    "email": "dana_vock@yahoo.com",
    "web": "http://www.friedmonteesq.com.au"
  },
  {
    "first_name": "Roy",
    "last_name": "Nybo",
    "company_name": "Phoenix Phototype",
    "address": "823 Fishers Ln",
    "state": "ACT",
    "post": 2603,
    "city": "Red Hill",
    "phone1": "02-5311-7778",
    "phone2": "0416-394-795",
    "email": "rnybo@nybo.net.au",
    "web": "http://www.phoenixphototype.com.au"
  },
  {
    "first_name": "Annamae",
    "last_name": "Lothridge",
    "company_name": "Highland Meadows Golf Club",
    "address": "584 Meridian St #997",
    "state": "ACT",
    "post": 2608,
    "city": "Civic Square",
    "phone1": "02-1919-3941",
    "phone2": "0495-759-817",
    "email": "alothridge@hotmail.com",
    "web": "http://www.highlandmeadowsgolfclub.com.au"
  },
  {
    "first_name": "Katheryn",
    "last_name": "Lamers",
    "company_name": "Sonoco Products Co",
    "address": "62171 E 6th Ave",
    "state": "ACT",
    "post": 2609,
    "city": "Fyshwick",
    "phone1": "02-4885-1611",
    "phone2": "0497-455-126",
    "email": "katheryn_lamers@gmail.com",
    "web": "http://www.sonocoproductsco.com.au"
  },
  {
    "first_name": "Jamie",
    "last_name": "Kushnir",
    "company_name": "Bell Electric Co",
    "address": "3216 W Wabansia Ave",
    "state": "ACT",
    "post": 2901,
    "city": "Tuggeranong Dc",
    "phone1": "02-4623-8120",
    "phone2": "0426-830-817",
    "email": "jamie@kushnir.net.au",
    "web": "http://www.bellelectricco.com.au"
  },
  {
    "first_name": "Wenona",
    "last_name": "Carmel",
    "company_name": "Maier, Kristine M",
    "address": "44 Bush St",
    "state": "NSW",
    "post": 1220,
    "city": "Grosvenor Place",
    "phone1": "02-2832-1545",
    "phone2": "0439-849-209",
    "email": "wenona@gmail.com",
    "web": "http://www.maierkristinem.com.au"
  },
  {
    "first_name": "Deane",
    "last_name": "Haag",
    "company_name": "Malsbary Mfg Co",
    "address": "9 Hamilton Blvd #299",
    "state": "NSW",
    "post": 1235,
    "city": "Sydney South",
    "phone1": "02-9718-2944",
    "phone2": "0453-828-758",
    "email": "dhaag@hotmail.com",
    "web": "http://www.malsbarymfgco.com.au"
  },
  {
    "first_name": "Nenita",
    "last_name": "Mckenna",
    "company_name": "Southern Imperial Inc",
    "address": "709 New Market St",
    "state": "NSW",
    "post": 1455,
    "city": "Botany",
    "phone1": "02-5059-2649",
    "phone2": "0419-730-349",
    "email": "nmckenna@yahoo.com",
    "web": "http://www.southernimperialinc.com.au"
  },
  {
    "first_name": "Mayra",
    "last_name": "Bena",
    "company_name": "Buelt, David L Esq",
    "address": "808 Glen Cove Ave",
    "state": "NSW",
    "post": 1595,
    "city": "Lane Cove",
    "phone1": "02-1455-6085",
    "phone2": "0453-666-885",
    "email": "mayra.bena@gmail.com",
    "web": "http://www.bueltdavidlesq.com.au"
  },
  {
    "first_name": "Samuel",
    "last_name": "Arellanes",
    "company_name": "Ryan, Barry M Esq",
    "address": "286 Santa Rosa Ave",
    "state": "NSW",
    "post": 1595,
    "city": "Lane Cove",
    "phone1": "02-7995-6787",
    "phone2": "0446-710-661",
    "email": "samuel.arellanes@arellanes.net.au",
    "web": "http://www.ryanbarrymesq.com.au"
  }
];
